# Lab 1 - Exploratory Data Analysis

First, we import libraries and load the dataset. We will be working with the `weather.norminal.arff`file first.

In [ ]:
import pandas as pd
import numpy as np
from scipy.io import arff # A library to load arff files

# Load the .arff file using scipy
data, meta = arff.loadarff('weather.norminal.arff')

# Convert the raw data into a pandas DataFrame
df = pd.DataFrame(data)

# Take a quick look at the first 5 rows
df.head()

       outlook  temperature  humidity     windy    play
0     b'sunny'         85.0      85.0  b'FALSE'   b'no'
1     b'sunny'         80.0      90.0   b'TRUE'   b'no'
2  b'overcast'         83.0      86.0  b'FALSE'  b'yes'
3     b'rainy'         70.0      96.0  b'FALSE'  b'yes'
4     b'rainy'         68.0      80.0  b'FALSE'  b'yes'

*Note:* When using `scipy.io.arff`, string/nominal columns are often loaded as byte strings (e.g., b'yes' or b'no). 

The following code will decode these into regular strings.

In [11]:
# Decode any byte-string columns to utf-8 strings
for col in df.select_dtypes([object]).columns:
    # Check if the first non-null element is bytes
    sample = df[col].dropna().iloc[0] if not df[col].dropna().empty else None
    if isinstance(sample, bytes):
        df[col] = df[col].str.decode('utf-8')

# Verify the first few rows now
df.head()

    outlook  temperature  humidity  windy play
0     sunny         85.0      85.0  FALSE   no
1     sunny         80.0      90.0   TRUE   no
2  overcast         83.0      86.0  FALSE  yes
3     rainy         70.0      96.0  FALSE  yes
4     rainy         68.0      80.0  FALSE  yes

## Inspect Data Types and Check for Missing Values

We will now check for basic information about our table:
- Row count

For each attribute:
- The number of non-null entries (data item count)
- The data type
- Count of missing values
- The percentage of missing values

In [25]:
# Check basic info (row count, non-null counts, and data types)
df.info()

print("-" * 40) # Divider line for clarity

# Check the exact count of missing values per column
print("# of Missing Values per Column:")
missing_counts = df.isnull().sum()
for col, count in missing_counts.items():
    # left-aligns the column name in a 15-character space
    print(f"{col:<15} | {count}")

print("-" * 40) # Divider line for clarity

# Calculate the percentage of missing values (if any)
print("Missing Percentage per Column:")
missing_percentage = (df.isnull().sum() / len(df)) * 100
for col, pct in missing_percentage.items():

    # {pct:.2f} rounds the percentage to 2 decimal places
    print(f"{col:<15} | {pct:.2f}%")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   outlook      14 non-null     object
 1   temperature  14 non-null     float64
 2   humidity     14 non-null     float64
 3   windy        14 non-null     object
 4   play         14 non-null     object
dtypes: float64(2), object(3)
memory usage: 688.0+ bytes
----------------------------------------
# of Missing Values per Column:
outlook         | 0
temperature     | 0
humidity        | 0
windy           | 0
play            | 0
----------------------------------------
Missing Percentage per Column:
outlook         | 0.00%
temperature     | 0.00%
humidity        | 0.00%
windy           | 0.00%
play            | 0.00%

## Analyzing Categorical Attributes

For each attribute, our goal in this section is to find:

1. The total number of unique values/categories.

2. The exact list of unique values and how many times each one appears in the dataset (their frequency).

In [ ]:
# Loop through all columns that are stored as objects (strings/categories)
for col in df.select_dtypes(include=['object', 'category']).columns:
    print(f"=== Attribute: {col} ===")
    
    # 1. Find the number of unique values
    cardinality = df[col].nunique()
    print(f"Number of categories: {cardinality}")
    
    # 2. Get each unique value and its frequency count
    print("Value      | Frequency")
    print("-" * 25) 
    counts = df[col].value_counts()
    
    # Loop through each unique value and its count
    for val, freq in counts.items():
        # left-alignment formatting so frequencies line up nicely
        print(f"{val:<10} | {freq}")
    print("-" * 40)

=== Attribute: outlook ===
Number of categories: 3
Value      | Frequency
--------------------
sunny      | 5
rainy      | 5
overcast   | 4
----------------------------------------
=== Attribute: windy ===
Number of categories: 2
Value      | Frequency
--------------------
FALSE      | 8
TRUE       | 6
----------------------------------------
=== Attribute: play ===
Number of categories: 2
Value      | Frequency
--------------------
yes        | 9
no         | 5
----------------------------------------

## Analyzing Numeric Attributes

For any continuous or numeric attribute, we will find:

1. **Range, Min, and Max**: The smallest value, largest value, and the span between them.

2. **Average**: The arithmetic mean.

3. **Three Most Frequent Values**: The three most common values in that column and how many times they appear.

In [30]:
# Loop through all columns that contain numbers
for col in df.select_dtypes(include=[np.number]).columns:
    print(f"=== Attribute: {col} ===")
    
    # 1. Find Min, Max, and Range
    min_val = df[col].min()
    max_val = df[col].max()
    range_val = max_val - min_val
    print(f"Range: {range_val} (Min: {min_val}, Max: {max_val})")
    
    # 2. Find Average (Mean)
    avg_val = df[col].mean()
    print(f"Average: {avg_val:.2f}")
    
    # 3. Find top three most frequent values and their frequencies
    print("Top 3 Most Frequent Values:")
    top_three = df[col].value_counts().head(3) # Fetch top 3 rows
    for val, freq in top_three.items():
        print(f"{val:<10} | {freq}")
        
    print("-" * 40)

=== Attribute: temperature ===
Range: 21.0 (Min: 64.0, Max: 85.0)
Average: 73.57
Top 3 Most Frequent Values:
75.0       | 2
72.0       | 2
85.0       | 1
----------------------------------------
=== Attribute: humidity ===
Range: 31.0 (Min: 65.0, Max: 96.0)
Average: 81.64
Top 3 Most Frequent Values:
70.0       | 3
90.0       | 2
80.0       | 2
----------------------------------------